action.GenerateGetterAction.text=____all____
action.GenerateShebangAction.text=Shebang Line
action.OptimizeDunderAllAction.text=Optimize ____all____
popup.GenerateShebangAction.ad_text=Will override original Shebang line
popup.GenerateShebangAction.title=Select Shebang